# Generated by Django 5.0.6 on 2024-07-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModels',
            new_name='BookModel',
        ),
    ]
