# Generated by Django 5.0.6 on 2024-07-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingmodel',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
