# Generated by Django 5.0.6 on 2024-07-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowingmodel_borrow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingmodel',
            name='book_id',
        ),
        migrations.AddField(
            model_name='borrowingmodel',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel'),
        ),
    ]
