# Generated by Django 5.0.6 on 2024-07-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_borrowingmodel_book_borrowingmodel_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowingModel',
        ),
    ]
