# Generated by Django 5.0.6 on 2024-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
